version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3556:3556"
    environment:
      MONGO_URI: ${MONGO_URI}  # L'URI MongoDB depuis le fichier .env
    volumes:
      - .:/app
      - /app/node_modules
