version: '3.8'
services:
  app:
    build: .
    ports:
      - "3556:3556"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
